### ISSUE TITLE
concern over requirements.txt

### ISSUE THREAD

**Issue by tatmush** [HITpyDevs/website#1]
`pip install -r requirements.txt` is not running successfully on windows. I believe there are a lot of unnecessary modules that are not being used e.g matplotlib, @Kayt  
[requirements - Copy.txt](https://github.com/HITpyDevs/website/files/1821463/requirements.-.Copy.txt)

**Comment by Kayt** [comment]
very sorry about that i might have to rebuild that file

**Comment by tatmush** [comment]
I made a new requirements.txt. @Kayt
